name: rise-text
channels:
  - conda-forge
dependencies:
  - gensim
  - nltk
  - pandas
  - matplotlib
  - notebook
  - ca-certificates
  - certifi
  - openssl
  - pip=22.3.1
  - pip:
    - rise==5.7.1
